CREATE TABLE Aliases (
	ID		BIGINT NOT NULL,
	Username	VARCHAR(255) NOT NULL,
	ProjectID	BIGINT NOT NULL,
	Alias		VARCHAR(255) NOT NULL,
	FullName	VARCHAR(255),

	CreateAt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(ID),
	UNIQUE(ProjectID, Alias),
	FOREIGN KEY(Username) REFERENCES Users(Username) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE
);
