CREATE TABLE Emails (
	Username	VARCHAR(255) NOT NULL,
	PriorityOrder	INT NOT NULL,
	Email		VARCHAR(255) NOT NULL,

	CreateAt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(Username, PriorityOrder),
	UNIQUE(Email),
	FOREIGN KEY(Username) REFERENCES Users(Username) ON DELETE CASCADE ON UPDATE CASCADE
);
