CREATE TABLE APIKeys (
	Token		VARCHAR(255) NOT NULL,
	ProjectID	BIGINT NOT NULL,
	Requester	VARCHAR(255) NOT NULL,
	RoleID		BIGINT,
	CreateAt	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	TTL		BIGINT check (TTL >= 0),
	PRIMARY KEY(Token),
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE, 
	FOREIGN KEY(Requester) REFERENCES Users(Username) ON DELETE CASCADE,
	FOREIGN KEY(RoleID) REFERENCES Roles(ID) ON DELETE SET NULL
);
