CREATE TABLE APIKeys (
	Token		VARCHAR(255),
	ProjectID	BIGINT,
	Requester	VARCHAR(255),
	RoleID		BIGINT,
	CreateAt	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	TTL		BIGINT,
	PRIMARY KEY(Token),
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID),
	FOREIGN KEY(Requester) REFERENCES Users(Username),
	FOREIGN KEY(RoleID) REFERENCES Roles(ID)
);
