CREATE TABLE Members (
	Username	VARCHAR(255) NOT NULL,
	ProjectID	BIGINT NOT NULL,
	RoleID		BIGINT NOT NULL,
	PRIMARY KEY(Username, ProjectID, RoleID),
	FOREIGN KEY(Username) REFERENCES Users(Username) ON DELETE CASCADE,
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE,
	FOREIGN KEY(RoleID) REFERENCES Roles(ID) ON DELETE CASCADE
);
