CREATE TABLE Members (
	Username	VARCHAR(255) NOT NULL,
	ProjectID	BIGINT NOT NULL,
	RoleID		BIGINT NOT NULL,

	CreateAt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(Username, ProjectID),
	FOREIGN KEY(Username) REFERENCES Users(Username) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE,
	FOREIGN KEY(RoleID) REFERENCES Roles(ID) ON DELETE CASCADE
);
