CREATE TABLE Phones (
	Username	VARCHAR(255) NOT NULL,
	PriorityOrder		INT NOT NULL,
	Number		VARCHAR(255) NOT NULL,

	CreateAt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	PRIMARY KEY(Username, PriorityOrder),
	UNIQUE(Number),
	FOREIGN KEY(Username) REFERENCES Users(Username) ON DELETE CASCADE, ON UPDATE CASCADE
);
