CREATE TABLE Privileges (
	ID		BIGINT NOT NULL,
	ProjectID	BIGINT NOT NULL,
	Name		VARCHAR(255) NOT NULL,
	Description	Text,
	PrivilegeGroup	VARCHAR(255),
	PriorityOrder	INT,

	CreateAt     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(ID),
	UNIQUE(ProjectID, Name),
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE
);
