CREATE TABLE Projects (
	ID		BIGINT NOT NULL,
	Owner		VARCHAR(255) NOT NULL,
	Name		VARCHAR(255) NOT NULL,
	
	CreateAt	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (ID),
	FOREIGN KEY (Owner) REFERENCES Users(Username) ON DELETE RESTRICT, ON UPDATE CASCADE
);
