CREATE TABLE Projects (
	ID		BIGINT NOT NULL,
	Owner		VARCHAR(255) NOT NULL,
	Name		VARCHAR(255) NOT NULL,
	CreateAt	TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (Owner) REFERENCES Users(Username) ON DELETE RESTRICT
);
