CREATE TABLE Roles (
	ID		BIGINT NOT NULL,
	ProjectID	BIGINT NOT NULL,
	Name		VARCHAR(255) NOT NULL,
	PriorityOrder	INT,
	
	CreateAt	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY(ID),
	UNIQUE(ProjectID, Name),
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE
);
