CREATE TABLE Settings (
	ProjectID	BIGINT NOT NULL,
	RedirectURL	VARCHAR(255),
	Credential	VARCHAR(255),
	AllowAlias	BOOLEAN DEFAULT TRUE,

	CreateAt	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(ProjectID),
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE
);
