CREATE TABLE Settings (
	ProjectID	BIGINT NOT NULL,
	RedirectURL	VARCHAR(255),
	Credential	VARCHAR(255),
	AllowAlias	BOOLEAN DEFAULT TRUE,
	PRIMARY KEY(ProjectID),
	FOREIGN KEY(ProjectID) REFERENCES Projects(ID) ON DELETE CASCADE
);
