CREATE TABLE Users (
	Username	VARCHAR(255) NOT NULL,
	Password	VARCHAR(256) NOT NULL,
	FirstName	VARCHAR(255) NOT NULL,
	LastName	VARCHAR(255) NOT NULL,
	Birthday	DATE,

	CreateAt	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LastModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(Username)
);
