CREATE TABLE users (
	username	VARCHAR(255) NOT NULL,
	password	VARCHAR(256) NOT NULL,
	firstname	VARCHAR(255) NOT NULL,
	lastname	VARCHAR(255) NOT NULL,
	birthday	DATE,

	create_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	update_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(username)
);
