CREATE TABLE projects (
	id			UUID NOT NULL,
	owner		VARCHAR(255) NOT NULL,
	name		VARCHAR(255) NOT NULL,
	
	create_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	FOREIGN KEY (owner) REFERENCES users(username) ON DELETE RESTRICT ON UPDATE CASCADE
);
