-- +goose Up
CREATE TABLE projects (
	id			UUID NOT NULL,
	owner		UUID NOT NULL,
	name		VARCHAR(255) NOT NULL,
	
	created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	FOREIGN KEY (owner) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- +goose Down
DROP TABLE projects;