CREATE TABLE aliases (
	id			BIGINT NOT NULL,
	username	VARCHAR(255) NOT NULL,
	project_id	UUID NOT NULL,
	alias		VARCHAR(255) NOT NULL,
	fullname	VARCHAR(255),

	create_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(id),
	UNIQUE(project_id, alias),
	FOREIGN KEY(username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
);
