-- +goose Up
CREATE TABLE aliases (
	id			BIGINT NOT NULL,
	user_id		UUID NOT NULL,
	project_id	UUID NOT NULL,
	alias		VARCHAR(255) NOT NULL,
	fullname	VARCHAR(255),

	created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(id),
	UNIQUE(project_id, alias),
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE aliases;