-- +goose Up
CREATE TABLE members (
	username	VARCHAR(255) NOT NULL,
	project_id	UUID NOT NULL,
	role_id		BIGINT NOT NULL,

	create_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	PRIMARY KEY(username, project_id),
	FOREIGN KEY(username) REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(project_id) REFERENCES projects(ID) ON DELETE CASCADE,
	FOREIGN KEY(role_id) REFERENCES roles(ID) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE members;