-- +goose Up
CREATE TABLE api_keys (
	token		VARCHAR(255) NOT NULL,
	project_id	UUID NOT NULL,
	requester	VARCHAR(255) NOT NULL,
	role_id		BIGINT NOT NULL,

	create_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	update_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expire_at	TIMESTAMP NOT NULL,

	PRIMARY KEY(token),
	FOREIGN KEY(project_id) REFERENCES Projects(ID) ON DELETE CASCADE, 
	FOREIGN KEY(requester) REFERENCES Users(Username) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(role_id) REFERENCES Roles(ID) ON DELETE SET NULL
);

-- +goose Down
DROP TABLE api_keys;