-- +goose Up
CREATE TABLE api_keys (
	token		VARCHAR(255) NOT NULL,
	project_id	UUID NOT NULL,
	requester	UUID NOT NULL,
	role_id		UUID NOT NULL,

	created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expired_at	TIMESTAMP NOT NULL,

	PRIMARY KEY(token),
	FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE, 
	FOREIGN KEY(requester) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE SET NULL
);

-- +goose Down
DROP TABLE api_keys;